import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <div className="bg-white">
          <div className="relative isolate px-6 pt-14 pb-14 lg:px-8">
            <div className="mx-auto max-w-2xl">
              {children}
            </div>
            <div
                className="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]"
                aria-hidden="true">
            </div>
          </div>
        </div>
      </main>
    </body>
    </html>
);
}
